### ISSUE TITLE
Interop-Config classed as optional dependency but is required.

### ISSUE THREAD

**Issue by bweston92** [prooph/psr7-middleware#30]
Just come across this problem my self, read the docs and read that interop-config is __required__ however it is only a development dependency.

https://github.com/prooph/psr7-middleware/blob/master/docs/book/factories.md#requirements point 2.
https://github.com/prooph/psr7-middleware/blob/master/composer.json#L56

**Comment by prolic** [comment]
Imho the docs should be changed, what do you think @codeliner ?

**Comment by sandrokeil** [comment]
@bweston92 You need interop-config if you want to use the factories in your app, like `psr-container`. It's only required for tests. I think the docs are correct.

**Comment by bweston92** [comment]
@sandrokeil so you're saying the docs are for development environments?

**Comment by prolic** [comment]
The factories are optional and not a requirement for this middleware I
think.

**Comment by sandrokeil** [comment]
@bweston92 no. @prolic Yes, it's like in the other components too. 

We need these dependencies only for unit tests, that's why it's defined in `required-dev`. If you want to use [any of these factories](https://github.com/prooph/psr7-middleware/tree/master/src/Container) you have to require interop-config. That's what the docs said. Is there any misleading in the docs and how can we solve it?

**Comment by bweston92** [comment]
@sandrokeil now I think about it the docs are right as it is in the context of factories which is obviously scenario the `interop-config` required.
